import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, describe, expect, it } from 'vitest';
import {
  PROOF_BUNDLE_CONTRACT_VERSION,
  type EvidenceKind,
  type EvidenceReference,
  type ProofBoundary,
  type ProofBundle,
} from '../evidence/contract.js';
import { sha256Digest } from '../evidence/validate.js';
import { importPlaywrightTraceFixture } from '../browser/import-playwright-trace.js';
import { captureTerminal } from '../terminal/adapter.js';
import { compileReviewBundle } from './compiler.js';

const roots: string[] = [];
const at = '2026-07-28T01:00:00.000Z';
const adapter = { namespace: 'dev.noaa.oiss.review-fixture', version: '1.0.0' };
const source = {
  kind: 'git' as const,
  repository: 'https://example.test/proofshot.git',
  head: '750b8a70e78b71b7bfe178d542db1fcaa93eee1d',
  ref: 'fixture',
  worktree: 'clean' as const,
};
const provenance = { producer: 'proofshot review fixture', producedAt: at, adapter, source };

afterEach(async () => {
  await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

function fixture(): { bundle: ProofBundle; content: Map<string, string> } {
  const values = [
    ['terminal', 'terminal', '{"exitCode":0}\n'],
    ['file', 'generated_file', '<h1>portable result</h1>'],
    ['url', 'url', '<h1>portable result</h1>'],
    ['deployment', 'deployment', '{"deploymentId":"deploy-42","buildId":"build-42"}'],
    ['browser', 'browser', '{"heading":"portable result","captureHealth":"observed"}'],
    ['screenshot', 'browser', 'PNG fixture bytes'],
  ] as const;
  const content = new Map<string, string>();
  const evidence: EvidenceReference[] = values.map(([id, kind, value]) => {
    const uri = `fixture/${id}`;
    content.set(uri, value);
    return {
      id: `evidence-${id}`,
      kind: kind as EvidenceKind,
      uri,
      digest: sha256Digest(value),
      sizeBytes: Buffer.byteLength(value),
      mediaType: id === 'file' || id === 'url'
        ? 'text/html'
        : id === 'screenshot' ? 'image/png' : 'application/json',
      provenance: id === 'deployment'
        ? { ...provenance, target: { class: 'deployed', locator: 'https://fixture.test', deploymentId: 'deploy-42', buildId: 'build-42', sourceRevision: source.head } }
        : provenance,
      access: { accessible: true, checkedAt: at, scope: 'reviewers', expiresAt: '2026-08-28T01:00:00.000Z' },
      retention: { policy: '30-days', retainUntil: '2026-08-28T01:00:00.000Z' },
      redaction: { policy: 'fixture-safe', applied: false },
    };
  });
  const expectedKinds: EvidenceKind[][] = [
    ['terminal'], ['generated_file', 'url'], ['deployment'], ['browser'],
  ];
  const expected = ['command', 'artifact', 'deployment', 'rendered'].map((id, index) => ({
    id: `expected-${id}`,
    description: [
      'Command completes successfully',
      'Command produces the expected file and portable URL capture',
      'Deployment identity is immutable and source-bound',
      'Browser surface renders the expected heading',
    ][index],
    expectation: { evaluator: adapter, predicate: { fixture: id } },
    requiredEvidence: expectedKinds[index],
  }));
  const actualEvidence = [
    ['evidence-terminal'],
    ['evidence-file', 'evidence-url'],
    ['evidence-deployment'],
    ['evidence-browser', 'evidence-screenshot'],
  ];
  const boundaryIds = ['command-runtime', 'artifact-readback', 'deployment-target', 'rendered-browser'];
  const actual = expected.map((item, index) => ({
    id: `actual-${item.id.slice(9)}`,
    expectedObservationId: item.id,
    completedAt: at,
    collectionOutcome: 'completed' as const,
    conclusion: 'matches' as const,
    description: `Fixture observed ${item.id.slice(9)}`,
    observedValue: { fixture: item.id.slice(9) },
    evidenceIds: actualEvidence[index],
    proofBoundaryIds: [boundaryIds[index], 'unit-fixture'],
    provenance: index === 2
      ? { ...provenance, target: { class: 'deployed', locator: 'https://fixture.test', deploymentId: 'deploy-42', buildId: 'build-42', sourceRevision: source.head } }
      : provenance,
    provenanceDrift: { detected: false },
  }));
  const boundaries: ProofBoundary[] = [
    {
      id: 'command-runtime', kind: 'local_runtime', description: 'Runs the fixture command locally.', exercised: true,
      observationIds: ['actual-command'], evidenceIds: ['evidence-terminal'],
      doesNotProve: ['Generated artifact content', 'deployed identity', 'rendered browser output', 'human acceptance'],
    },
    {
      id: 'artifact-readback', kind: 'readback', description: 'Reads exact generated bytes and a captured URL response.', exercised: true,
      observationIds: ['actual-artifact'], evidenceIds: ['evidence-file', 'evidence-url'],
      doesNotProve: ['Deployment identity', 'browser rendering', 'human acceptance'],
    },
    {
      id: 'deployment-target', kind: 'deployment', description: 'Records immutable deployment and target identity.', exercised: true,
      observationIds: ['actual-deployment'], evidenceIds: ['evidence-deployment'],
      doesNotProve: ['Rendered browser output', 'human acceptance'],
    },
    {
      id: 'rendered-browser', kind: 'local_runtime', description: 'Observes the resulting browser surface.', exercised: true,
      observationIds: ['actual-rendered'], evidenceIds: ['evidence-browser'],
      doesNotProve: ['Artifact byte identity', 'stakeholder or human acceptance'],
    },
    {
      id: 'source-static', kind: 'source_static', description: 'Inspects the source-controlled fixture and storage evaluation.', exercised: true,
      observationIds: [], evidenceIds: [],
      doesNotProve: ['Runtime behavior', 'live storage behavior', 'human acceptance'],
    },
    {
      id: 'unit-fixture', kind: 'unit_fixture', description: 'Exercises the complete mixed-evidence compiler fixture.', exercised: true,
      observationIds: actual.map(({ id }) => id), evidenceIds: evidence.map(({ id }) => id),
      doesNotProve: ['Live deployment behavior', 'stakeholder or human acceptance'],
    },
    {
      id: 'human-acceptance', kind: 'human_acceptance', description: 'Reserved for independent reviewer acceptance.', exercised: false,
      observationIds: [], evidenceIds: [],
      doesNotProve: ['Acceptance because this boundary was not exercised'],
    },
  ];
  return {
    content,
    bundle: {
      contractVersion: PROOF_BUNDLE_CONTRACT_VERSION,
      id: 'odo-mixed-review-fixture',
      createdAt: at,
      provenance,
      claims: [{
        id: 'claim-portable-surface',
        statement: 'The ODO-style command produced a content-addressed surface that was deployed and observed in a browser.',
        expectedObservationIds: expected.map(({ id }) => id),
        actualObservationIds: actual.map(({ id }) => id),
      }],
      expectedObservations: expected,
      actualObservations: actual,
      evidence,
      proofBoundaries: boundaries,
      nonclaims: [{
        id: 'not-accepted',
        statement: 'A stakeholder accepted the result.',
        reason: 'The human-acceptance boundary was not exercised.',
        claimIds: ['claim-portable-surface'],
        proofBoundaryIds: ['human-acceptance'],
      }],
    },
  };
}

const policy = {
  budgets: { perItemBytes: 1024, totalBytes: 4096 },
  retention: { policy: '30-days', retainUntil: '2026-08-28T01:00:00.000Z' },
  access: { scope: 'reviewers', expiresAt: '2026-08-28T01:00:00.000Z' },
  privacy: {
    policy: 'sanitized structured evidence only; raw recordings excluded',
    rawTerminalVideo: 'excluded' as const,
    rawBrowserVideo: 'excluded' as const,
  },
};

describe('mixed review bundle compiler', () => {
  it('compiles claim-centric portable outputs while keeping every proof boundary distinct', async () => {
    const root = await mkdtemp(join(process.cwd(), '.proofshot-review-test-'));
    roots.push(root);
    const { bundle, content } = fixture();
    const result = await compileReviewBundle({
      bundle, evidence: content, outputDirectory: root, policy,
      captureHealth: { terminal: 'observed', browser: 'observed', video: 'not_observed' },
      postTrimMediaDurationSeconds: 7.25,
      now: new Date(at),
    });

    expect(result.manifest.semanticStatus).toMatchObject({
      valid: true,
      result: 'pass',
      claims: [{ claimId: 'claim-portable-surface', status: 'pass' }],
    });
    expect(result.manifest.proofBoundaries.map(({ id }) => id)).toEqual(expect.arrayContaining([
      'command-runtime', 'artifact-readback', 'deployment-target', 'rendered-browser',
      'source-static', 'unit-fixture', 'human-acceptance',
    ]));
    expect(result.manifest.contentSize).toMatchObject({ itemCount: 6, uniqueObjectCount: 5 });
    const summary = await readFile(result.paths.summary, 'utf8');
    expect(summary).toContain('[Open the portable viewer](./viewer.html)');
    expect(summary).toContain('Post-trim media duration: 7.25 seconds');
    expect(summary).not.toContain('wall-clock session');
    const viewer = await readFile(result.paths.viewer!, 'utf8');
    expect(viewer).toContain('<strong>Bundle contract:</strong> VALID');
    expect(viewer).toContain('<strong>Claim rollup:</strong> PASS');
    expect(viewer).toContain('No-video fallback');
    expect(viewer).toContain('Open raw manifest JSON');
    expect(viewer).toContain(':focus-visible');
    expect(viewer).toContain('Does not prove');
    expect(viewer).toContain('alt="Evidence evidence-screenshot preview — presentation only, not proof of a claim"');
  });

  it('keeps missing or tampered evidence visible and prevents a pass', async () => {
    const root = await mkdtemp(join(process.cwd(), '.proofshot-review-test-'));
    roots.push(root);
    const { bundle, content } = fixture();
    content.set('fixture/browser', 'tampered bytes');
    content.delete('fixture/deployment');
    const result = await compileReviewBundle({
      bundle, evidence: content, outputDirectory: root, policy, now: new Date(at),
    });
    expect(result.manifest.semanticStatus.valid).toBe(false);
    expect(result.manifest.semanticStatus.claims[0].status).toBe('inconclusive');
    expect(result.manifest.semanticStatus.issues.map(({ code }) => code)).toEqual(expect.arrayContaining([
      'digest_mismatch', 'missing_evidence_content',
    ]));
    expect(await readFile(result.paths.summary, 'utf8')).toContain('INVALID — FAIL CLOSED');
    expect(await readFile(result.paths.viewer!, 'utf8')).toContain('digest_mismatch');
  });

  it('downgrades required blocked capture and understated or over-budget bytes', async () => {
    const root = await mkdtemp(join(process.cwd(), '.proofshot-review-test-'));
    roots.push(root);
    const { bundle, content } = fixture();
    const oversized = 'x'.repeat(2048);
    const browser = bundle.evidence.find(({ id }) => id === 'evidence-browser')!;
    browser.digest = sha256Digest(oversized);
    browser.sizeBytes = 1;
    content.set('fixture/browser', oversized);
    const result = await compileReviewBundle({
      bundle, evidence: content, outputDirectory: root, policy,
      captureHealth: { terminal: 'observed', browser: 'blocked' },
      now: new Date(at),
    });
    expect(result.manifest.semanticStatus).toMatchObject({ valid: false, result: 'inconclusive' });
    expect(result.manifest.semanticStatus.issues.map(({ code }) => code)).toEqual(expect.arrayContaining([
      'capture_blocked', 'declared_size_mismatch', 'item_budget_exceeded',
    ]));
    expect(result.manifest.objects.find(({ digest }) => digest === browser.digest)).toMatchObject({
      materialized: false,
      reason: 'per-item content budget is invalid or exceeded',
    });
  });

  it('runs an ODO-style producer, reads its file, and observes the derived browser surface', async () => {
    const root = await mkdtemp(join(process.cwd(), '.proofshot-review-test-'));
    roots.push(root);
    const output = join(root, 'portable-odo.html');
    const producer = fileURLToPath(new URL('../../test/fixtures/odo-generate-surface.cjs', import.meta.url));
    const terminal = await captureTerminal({
      argv: [process.execPath, producer, output],
      cwd: root,
      environment: { LANG: 'C.UTF-8', NO_COLOR: '1' },
      environmentAllowlist: ['LANG', 'NO_COLOR'],
      expectedJson: true,
      source,
      scenarioId: 'odo-produces-portable-surface',
      terminal: { columns: 88, rows: 24, color: false, glyphs: 'ascii', locale: 'C.UTF-8' },
      generatedArtifacts: [{
        id: 'portable-surface', kind: 'file', locator: output,
        sourcePath: output, mediaType: 'text/html',
      }],
    });
    expect(terminal.status).toBe('pass');
    expect(terminal.outcome.json).toMatchObject({ parsed: true });

    const html = await readFile(output, 'utf8');
    const heading = html.match(/<h1>([^<]+)<\/h1>/)?.[1];
    const browser = importPlaywrightTraceFixture([
      { type: 'action', name: 'open generated surface', status: 'completed', time: at },
      { type: 'capture', kind: 'dom', status: 'completed', value: { heading }, time: at },
      { type: 'capture', kind: 'console', status: 'completed', time: at },
      { type: 'capture', kind: 'network', status: 'completed', time: at },
    ], {
      target: {
        class: 'deployed_readonly', url: 'https://fixture.test/reports/portable-odo',
        origin: 'https://fixture.test', deploymentId: 'deploy-42', buildId: 'build-42',
        sourceRevision: source.head,
      },
      source,
      runtime: { browser: { name: 'fixture-browser' }, driver: { name: 'trace-fixture' } },
    }).observations[0];
    expect(browser.artifacts).toEqual(expect.arrayContaining([
      expect.objectContaining({ kind: 'dom', value: { heading: 'Portable ODO result' } }),
    ]));

    const { bundle, content } = fixture();
    const replacements = new Map<string, string>([
      ['evidence-terminal', `${JSON.stringify(terminal, null, 2)}\n`],
      ['evidence-file', html],
      ['evidence-url', html],
      ['evidence-browser', `${JSON.stringify(browser, null, 2)}\n`],
    ]);
    for (const [id, value] of replacements) {
      const reference = bundle.evidence.find((item) => item.id === id)!;
      reference.digest = sha256Digest(value);
      reference.sizeBytes = Buffer.byteLength(value);
      content.set(reference.uri, value);
    }
    bundle.actualObservations.find(({ id }) => id === 'actual-command')!.observedValue = terminal as never;
    bundle.actualObservations.find(({ id }) => id === 'actual-rendered')!.observedValue = browser as never;
    const result = await compileReviewBundle({
      bundle,
      evidence: content,
      outputDirectory: join(root, 'review'),
      policy: { ...policy, budgets: { perItemBytes: 64 * 1024, totalBytes: 256 * 1024 } },
      captureHealth: { terminal: 'observed', browser: 'observed', video: 'not_observed' },
      now: new Date(at),
    });
    expect(result.manifest.semanticStatus).toMatchObject({ valid: true, result: 'pass' });
    expect(result.manifest.proofBoundaries.find(({ id }) => id === 'human-acceptance')).toMatchObject({ exercised: false });
    expect(terminal.generatedArtifacts[0].digest).toBe(bundle.evidence.find(({ id }) => id === 'evidence-file')!.digest);
  });
});
