import * as fs from 'fs';
import * as path from 'path';
import { type VerificationResult, countErrors, countWarnings } from './bundle.js';

/**
 * Generate a markdown snippet suitable for a GitHub PR description.
 * Uses relative paths for screenshots (assumes artifacts are committed or linked).
 */
export function formatForPR(result: VerificationResult): string {
  const projectName = path.basename(process.cwd());
  const durationSec = Math.round(result.durationMs / 1000);

  let totalErrors = 0;
  let totalWarnings = 0;

  let md = `## Visual Verification — ProofShot

| Page | Status | Screenshot |
|------|--------|------------|
`;

  for (const page of result.pageResults) {
    const errors = countErrors(page.errors);
    const warnings = countWarnings(page.consoleOutput);
    totalErrors += errors;
    totalWarnings += warnings;

    const status = errors > 0 ? '⚠️ Errors' : '✅ OK';
    const relativeSS = path.relative(process.cwd(), page.screenshotPath);
    md += `| \`${page.page}\` | ${status} | ![${page.page}](${relativeSS}) |\n`;
  }

  md += `
**Framework:** ${result.framework} | **Pages:** ${result.pageResults.length} | **Errors:** ${totalErrors} | **Warnings:** ${totalWarnings} | **Duration:** ${durationSec}s
`;

  if (result.videoPath) {
    const relativeVideo = path.relative(process.cwd(), result.videoPath);
    md += `\n**Video:** [Session recording](${relativeVideo})\n`;
  }

  md += `\n<sub>Generated by [ProofShot](https://github.com/AmElmo/proofshot)</sub>\n`;

  return md;
}

/**
 * Write PR-formatted output to a file or stdout.
 */
export function writePRFormat(
  result: VerificationResult,
  outputPath?: string,
): string {
  const md = formatForPR(result);
  if (outputPath) {
    fs.writeFileSync(outputPath, md);
    return outputPath;
  }
  return md;
}

// ─── URL-based PR comment format (for GitHub upload) ───

export interface PRCommentData {
  description: string | null;
  sessionCount: number;
  screenshots: Map<string, string>; // filename → GitHub asset URL
  video: { url: string; renderMode: 'embed' | 'link' } | null;
  errorCount: number;
  branch: string;
  commitSha: string;
}

/**
 * Generate markdown for a GitHub PR comment with embedded uploaded assets.
 * Uses GitHub asset URLs so images and video render inline.
 */
export function formatPRComment(data: PRCommentData): string {
  let md = `## ProofShot Verification\n\n`;

  if (data.description) {
    md += `> ${data.description}\n\n`;
  }

  // Status
  const status =
    data.errorCount === 0
      ? '✅ No errors detected'
      : `⚠️ ${data.errorCount} error(s) detected`;
  md += `${status}\n\n`;

  // Video (GitHub renders video URLs as playable embeds)
  if (data.video) {
    md += `### Recording\n\n`;
    if (data.video.renderMode === 'embed') {
      md += `${data.video.url}\n\n`;
    } else {
      md += `[Session recording](${data.video.url})\n\n`;
    }
  }

  // Screenshots
  const screenshotEntries = [...data.screenshots.entries()];
  const storyboardEntry = screenshotEntries.find(([filename]) => isStoryboardFile(filename));
  const regularScreenshots = screenshotEntries.filter(([filename]) => !isStoryboardFile(filename));

  if (storyboardEntry) {
    const [filename, url] = storyboardEntry;
    const label = storyboardLabel(filename);
    md += `### Storyboard\n\n`;
    md += `![${label}](${url})\n\n`;
  }

  if (regularScreenshots.length > 0) {
    md += `### Screenshots\n\n`;

    if (regularScreenshots.length <= 3) {
      for (const [filename, url] of regularScreenshots) {
        const label = filename.replace(/\.png$/, '').replace(/^step-/, '');
        md += `**${label}**\n\n`;
        md += `![${label}](${url})\n\n`;
      }
    } else {
      md += `<details>\n<summary>View ${regularScreenshots.length} screenshots</summary>\n\n`;
      for (const [filename, url] of regularScreenshots) {
        const label = filename.replace(/\.png$/, '').replace(/^step-/, '');
        md += `**${label}**\n\n![${label}](${url})\n\n`;
      }
      md += `</details>\n\n`;
    }
  }

  // Footer
  md += `---\n`;
  md += `<sub>`;
  md += `Branch: \`${data.branch}\``;
  if (data.commitSha) {
    md += ` · Commit: \`${data.commitSha.slice(0, 7)}\``;
  }
  md += ` · ${data.sessionCount} session(s)`;
  md += `</sub>\n`;
  md += `<sub>Generated by [ProofShot](https://github.com/AmElmo/proofshot)</sub>\n`;

  return md;
}

function isStoryboardFile(filename: string): boolean {
  return path.basename(filename).toLowerCase().startsWith('storyboard');
}

function storyboardLabel(filename: string): string {
  return path.basename(filename).replace(/\.png$/i, '');
}
